import string

if __name__ == '__main__':
    values = {
        'name': 'kpatch-module-example',
        'patch_file': 'example.patch',
        'kmod_filename': 'kpatch-example.ko',
        'description': 'Package generated by kpatch-package-builder',
    }

    with open('kpatch-patch.spec') as f:
        spec_template = string.Template(f.read())

    print(spec_template.substitute(values))
